 const ttpQues = [
{ english : "Truthful",
hindi:'सत्यभाषी'},
{ english : "Being Sensitive",
hindi:'संवेदनशीलता'},
{ english : "Inquisitive",
hindi:'जिज्ञासू'},
{ english : "Observant",
hindi:'चौकस'},
{ english : "Flexibility",
hindi:'समायोज्य'},
{ english : "Creativity",
hindi:'रचनात्मकता'},
{ english : "Self Discipline",
hindi:'आत्म-अनुशासन'},
{ english : "Honesty",
hindi:'ईमानदारी'},
{ english : "Courageous",
hindi:'साहसी'},
{ english : "Patience",
hindi:'धीरज'},
{ english : "Kindness",
hindi:'दयालुता'},
{ english : "Loyalty",
hindi:'निष्ठा'},
{ english : "Gratitude",
hindi:'कृतज्ञता'},
{ english : "Industrious", 
hindi:'परिश्रमी'},
{ english : "Forgiving",
hindi:'क्षमाशील'},
{ english : "Fitness",
hindi:'तंदुरुस्ती'},
{ english : "Sharing",
hindi:'सहभाजी'},
{ english : "Perseverance",
hindi:'दृढ़ता'},
{ english : "Punctual",
hindi:'समयनिष्ठ'},
{ english : "Commitment",
hindi:'वचनबद्धता'},
{ english : "Pride", 
hindi:'गौरव'},
{ english : "Self-Respect",
hindi:'आत्म-सम्मान'},
{ english : "Self-Reliance", 
hindi:'आत्म-निर्भरता'},
{ english : "Self-Control",
hindi:'आत्म-नियंत्रण'},
{ english : "Ambitious", 
hindi:'महत्त्वाकांक्षी'},
{ english : "Resiliency",
hindi:'संकटकाल में मजबूत'},
{ english : "Focus", 
hindi:'एकाग्रता'},
{ english : "Will Power",
hindi:'इच्छा शक्ति'},
{ english : "Vision", 
hindi:'दूरदर्शिता'},
{ english : "Humility",
hindi:'विनम्रता'},
];
export {ttpQues} ;