const test4Ques = [
	{ english : "Truthfullness",
	hindi:'सच्चाई'},
	{ english : "Being Sensitive",
	hindi:'संवेदनशीलता'},
	{ english : "Inquisitive",
	hindi:'जिज्ञासू'},
	{ english : "Observant",
	hindi:'चौकस'},
	{ english : "Flexibility",
	hindi:'समायोज्य'},
	{ english : "Creativity",
	hindi:'रचनात्मकता'},
	{ english : "Self Discipline",
	hindi:'आत्म-अनुशासन'},
	{ english : "Honesty",
	hindi:'ईमानदारी'},
	{ english : "Courageous",
	hindi:'साहसी'},
	{ english : "Patience",
	hindi:'धीरज'},
	{ english : "Kindness",
	hindi:'दयालुता'},
	{ english : "Loyalty",
	hindi:'निष्ठा'},
	{ english : "Gratitude",
	hindi:'कृतज्ञता'},
	{ english : "Industrious", 
	hindi:'परिश्रमी'},
	{ english : "Forgiving",
	hindi:'क्षमाशील'},
	{ english : "Fitness",
	hindi:'तंदुरुस्ती'},
	{ english : "Sharing",
	hindi:'सहभाजी'},
	{ english : "Perseverance",
	hindi:'दृढ़ता'},
	{ english : "Punctual",
	hindi:'समयनिष्ठ'},
	{ english : "Commitment",
	hindi:'वचनबद्धता'},
	{ english : "Pride", 
	hindi:'गौरव'},
	{ english : "Self-Respect",
	hindi:'आत्म-सम्मान'},
	{ english : "Self-Reliance", 
	hindi:'आत्म-निर्भरता'},
	{ english : "Self-Control",
	hindi:'आत्म-नियंत्रण'},
	{ english : "Ambitious", 
	hindi:'महत्त्वाकांक्षी'},
	{ english : "Polite",
	hindi:'विनम्र'},
	{ english : "Hopefullness", 
	hindi:'आशावाद'},
	{ english : "Focussed",
	hindi:'एकाग्रता'},
	{ english : "Visionary", 
	hindi:'दूरदर्शिता'},
	{ english : "Organiszed",
	hindi:'संयोजित'},
	{ english : "Will Power",
	hindi:'इच्छा शक्ति'},
	{ english : "Success Orientedness", 
	hindi:'सफलता उन्मुखता'},
	{ english : "Excellence", 
	hindi:'श्रेष्ठता'},
	{ english : "Peacefullness",
	hindi:'शांति'},
	{ english : "Leadership Ability", 
	hindi:'नेतृत्व क्षमता'},
	{ english : "Resiliency",
	hindi:'संकटकाल में मजबूत'},
] ;
export { test4Ques } ;