 const ustopQues = [
 { english : "I am alert about my surroundings and my neighbourhood",
	hindi:'मैं अपने आस – पड़ोस और वातावरण को लेकर सतर्क रहता/रहती हूँ'},
 { english : "I can become easily irritated by others",
	hindi:'दूसरों के कारण मैं आसानी से क्रोधित हो जाता/जाती हूँ'},
	{ english : "I am rejected by people around me",
	hindi:'मेरे आस पास के लोग मुझे अस्वीकृत कर देते हैं'},
	{ english : "I am restless about things and activities that are happening around me",
	hindi:'अपनी आस – पास कि गतिविधियों के बारे में मैं अधीर हो जाता/जाती हूँ'},
	{ english : "I am not easily satisfied by others' explanation of things or events",
	hindi:'किसी कार्य या घटना को लेकर किसी अन्य व्यक्ति के स्पष्टीकरण से मैं संतुष्ट नहीं हो पाता/पाती हूँ'},
	{ english : "I am misunderstood by people around me",
	hindi:'अपने आस – पास के लोगो द्वारा मैं गलत समझा जाता/जाती हूँ '},
	{ english : "I feel nervous while doing things",
	hindi:'कार्यों को करते हुए मैं बेचैन हो जाता/जाती हूँ'},
	{ english : "I am unable to decide easily about things and events",
	hindi:'चीजों और घटनाओं को लेकर मैं जल्दी से फैसला नहीं ले पाता/पाती हूँ'},
	{ english : "I resort to crying while talking and explaining things to others",
	hindi:'दूसरों तक अपनी बात पहुंचाते हुए या उन्हें समझाते हुए मैं रोने लगता/लगती हूँ'},
	{ english : "I want to be in the company of others so that I feel secure",
	hindi:'खुद को सुरक्षित महसूस कराने के लिए मैं दूसरों का सहारा लेता/लेती हूँ'},
	{ english : "I am unable to concentrate on the task that I am doing",
	hindi:'जिस कार्य को मैं कर रहा हूँ उसपर ध्यान केन्द्रित नहीं कर पाता/पाती हूँ'},
	{ english : "I feel surrounded by unwanted negative thoughts in everything I do",
	hindi:' मैं जो भी कार्य करने जाता हूँ खुद को अनचाहे नकारात्मक विचारों से घिरा पाता/पाती हूँ'},
	{ english : "I keep thinking about things long after they are over and done with",
	hindi:' घटना को बीते हुए समय हो जाने पर भी मैं उसी के बारे में सोचता रहता/रहती हूँ'},
	{ english : "I am fearful about day to day events and harms they may cause", 
	hindi:' रोजाना की गतिविधियों से जो खतरें हो सकते है उनको लेकर मैं डरा रहता/रहती हूँ'},
	{ english : "I think my performance in my tasks and responsibilities is below my actual level",
	hindi:' मुझे लगता है कि कार्यों में मेरा प्रदर्शन और जिम्मेदारियां मेरी असली क्षमता से कम हैं '},
	{ english : "I avoid things and events that I am not comfortable about",
	hindi:' जिन चीजों और घटनाओं को लेकर मैं सहज महसूस नहीं कर रहा/रही हूँ उनसे मैं दूर रहता/रहती हूँ'},
	{ english : "I am not able to let go of things and events of the past",
	hindi:' पुरानी बातों और बीते हुए कल से मैं उभर नहीं पाता/पाती हूँ'},
	{ english : "Events and things stay in my mind and heart forever",
	hindi:' घटनाएँ और बातें मेरे दिलो-दिमाग में हमेशा रहती हैं'},
	{ english : "I often feel its not me but someone else inside me who is doing things",
	hindi:' मैं कई बार महसूस करता/करती हूँ कि मैं नहीं मेरे अन्दर कोई और है जो मेरे कार्य कर रहा है'},
	{ english : "I am conscious about losing control of things and events around me",
	hindi:' अपने आस – पास कि घटनाओं और गतिविधियों पर से नियंत्रण खोने को लेकर मैं सचेत रहता/रहती हूँ'},
	{ english : "I feel tired and drained out", 
	hindi:' मैं खुद को अत्यंत थका हुआ और कमज़ोर महसूस करता/करती हूँ'},
	{ english : "I experience sudden profuse sweating",
	hindi:' कई बार मैं अचानक पसीने-पसीने हो जाता/जाती हूँ'},
	{ english : "I can feel my heart thumping in my chest", 
	hindi:' मैं सीने में दिल को तेज़ी से धड़कते हुए महसूस कर पाता/पाती हूँ'},
	{ english : "I experienced disturbed sleep or no sleep at all",
	hindi:' मैं अशांत नींद या बिलकुल न सो पाना अनुभव करता/करती हूँ'},
	{ english : "I can feel visible trembling in my hands and legs", 
	hindi:' अपने हाथों और पैरों को तेज़ी से कांपता हुआ महसूस करता/करती हूँ'},
	{ english : "I feel faint while doing things",
	hindi:' कार्य करते वक्त मैं बेहोशी महसूस करता/करती हूँ '},
	{ english : "I run out of breath and need to sit calmly to become normal again", 
	hindi:' मेरी सांस फूल जाती है और मुझे दोबारा सामान्य महसूस करने के लिए कुछ देर विश्राम करना पड़ता है'},
	{ english : "I experience discomfort in my tummy/gas/constipation or loose motions",
	hindi:' मैं अपने पेट में तकलीफ या गैस / कब्ज़ / दस्त अनुभव करता/करती हूँ'},
	{ english : "I feel cold & numb in my toes & fingers", 
	hindi:' मैं अपने हाथों और पैरों कि उँगलियों को ठंडा या सुन्न अनुभव करता/करती हूँ'},
	{ english : "I feel like my chest is tight & I may choke",
	hindi:' मुझे छाती में भारीपन और घुटन महसूस होती है'},
	{ english : "Certain People, things or behaviours make me freak out and tensed",
	hindi:' कुछ लोग या बर्ताव मुझे तनाव या घबराहट में डाल देते हैं '},
	{ english : "I get tensed few times in a day", 
	hindi:' एक दिन में कुछ बार मैं तनाव महसूस करता/करती हूँ'},
	{ english : "My tensions stay with me for some time then they go away", 
	hindi:' मेरी परेशानियां कुछ वक्त तक मेरे साथ रहती हैं और फिर चली जाती हैं'},
	{ english : "Some events and situations make me concerned and apprehensive",
	hindi:' कुछ घटनाएं और स्थितियां मुझे चिंतित और आशंकित कर देतीं हैं'},
	{ english : "I think I am a tense and uneasy person", 
	hindi:' मुझे लगता है कि मैं एक परेशान और बेचैन आदमी हूँ'},
	{ english : "My tense state affects my daily routine",
	hindi:' मेरी तनावपूर्ण अवस्था मेरी रोजाना के कार्यों को प्रभावित करती है'},
	{ english : "I think I am worthless and non-contributing",
	hindi:' मुझे लगता है कि मैं बेकार हूँ और किसी के काम नहीं आ पाता/पाती हूँ'},
	{ english : "Life is a constant struggle and there is nothing much you can do about it",
	hindi:' मुझे लगता है कि ज़िन्दगी सिर्फ एक लम्बा संघर्ष है और हम इसके बारे में कुछ नहीं कर सकते'},
	{ english : "I feel there is no point in showing your capabilities, it is better to shut yourself down",
	hindi:' मुझे लगता है कि अपनी क्षमताओं का प्रदर्शन नहीं करना चाहिए और खुद को छुपा लेना ही सही है '},
	{ english : "I give up on things beyond a point and call it quits",
	hindi:' एक समय के बाद मैं चीजों से तंग आकर उन्हें छोड़ देता/देती हूँ'},
	{ english : "I do fingers tapping on flat surface and shake my legs while sitting",
	hindi:' मैं उँगलियों से ठक-ठक करता/करती रहता हूँ और बैठे वक्त पैर हिलाता/हिलाती हूँ'},
	{ english : "I eat the skin around my nails or bite my lips",
	hindi:' मैं अपने नाख़ून के आस पास और अपने होठों कि खाल को चबाता/चबाती हूँ'},
	{ english : "I bite my nails to keep them short", 
	hindi:' मैं अपने नाखुनों को छोटा रखने के लिए चबाता/चबाती हूँ'},
	{ english : "I experience situations where I am not able to speak. Even if I try to, my words just don't come out",
	hindi:' मैंने ऐसी स्थिति अनुभव कि है जहाँ मैं बोल नहीं पाता/पाती हूँ और कोशिश भी करूँ तो शब्द बाहर नहीं आते'},
	{ english : "I end up eating extra and then I regret doing that", 
	hindi:' मैं ज्यादा खाना खा लेता हूँ और फिर बाद में अफ़सोस करता/करती हूँ  '},
	{ english : "I resort to pricking, cutting or injuring self",
	hindi:' मैं खुद को नुकसान पहुचाता/पहुचाती हूँ जैसे नुकीली चीजें चुभाना या खुद को चोट करना '},
	{ english : "I experience relief in some situations only after having a smoke/whiskey/beverage",
	hindi:' कुछ घटनाओं के बाद, खुद को शांत करने के लिए मैं धुम्रपान / शराब या मदिरा का सहारा लेता/लेती हूँ '},
	{ english : "I absent myself from events and social engagements", 
	hindi:' मैं सामाजिक कार्यों और गतिविधियों से दूरी बनाये रखता/रखती हूँ'},
	{ english : "I pull my hair around my forehead, face or hands",
	hindi:' मैं अपने हाथ, छाती, चेहरे या सर के बालों को तोड़ता/तोड़ती हूँ'},
	{ english : "I am not able to go along well with friends and relatives long term",
	hindi:' मैं दोस्तों और रिश्तेदारों से लम्बे समय तक बनाकर नहीं रख पाता/पाती हूँ'},
];
export {ustopQues} ;
